#!/bin/bash

set -e

LOC=$(dirname $0)
CONF=${1:-${LOC}/perf-test-all.conf}

./bird -lc $CONF -P perftest.pid

function wait_for_done() {
  tail -f perftest.log | while read dd; do
#    echo $dd
    case $dd in
      *\ $1\ done\ with\ *)
        echo "protocol $1 done"
        exit 0
        ;;
      *\<BUG\>*)
        echo "something nasty happened";
        exit 42
        ;;
    esac
  done
}

for p in $(./birdc -l show protocols | sed -rn 's/(\S+)\s+Perf\s+.*/\1/p'); do
  echo "enabling protocol $p"
  ./birdc -l enable $p
  wait_for_done $p
  echo "disabling protocol $p"
  ./birdc -l disable $p
done

./birdc -l down
