#!/usr/bin/perl

use common::sense;
use Data::Dump;
use POSIX;
use Chart::Gnuplot;

my $clock_ticks = POSIX::sysconf( &POSIX::_SC_CLK_TCK );

my (@time, @unes, @minflt, @majflt, @utime, @stime, @rss);

while (<>) {
  next unless s/^Stats: //;
  chomp;
  my @data = split / /, $_;
  my ($time, $unes, $minflt, $majflt, $utime, $stime, $rss) = @data[(0, 1, 11, 13, 15, 16, 25)];
  { local $, = "\t"; say ($time, $unes, $minflt, $majflt, $utime / $clock_ticks, $stime / $clock_ticks, $rss); }
  map { eval "push \@$_, \$$_;"; } qw/time unes minflt majflt utime stime rss/;
}

my $chart = Chart::Gnuplot->new(
  output => "stat.ps",
  title => "Bird Resource Usage",
  xlabel => "Wall clock time (seconds)",
  ylabel => "(seconds)",
  y2label => "(count)",
  y2tics => {},
);

$chart->plot2d(
  Chart::Gnuplot::DataSet->new(
    xdata => \@time,
    ydata => [ map { ($_ - $utime[0])/$clock_ticks } @utime ],
    title => "userspace time",
    style => "lines",
  ),
  Chart::Gnuplot::DataSet->new(
    xdata => \@time,
    ydata => [ map { ($_ - $stime[0])/$clock_ticks } @stime ],
    title => "kernel time",
    style => "lines",
  ),
  Chart::Gnuplot::DataSet->new(
    xdata => \@time,
    ydata => [ map { $_ - $minflt[0] } @minflt ],
    title => "minor faults",
    style => "lines",
    axes => "x1y2",
  ),
  Chart::Gnuplot::DataSet->new(
    xdata => \@time,
    ydata => [ map { $_ - $majflt[0] } @majflt ],
    title => "major faults",
    style => "lines",
    axes => "x1y2",
  ),
  Chart::Gnuplot::DataSet->new(
    xdata => \@time,
    ydata => [ map { $_ - $rss[0] } @rss ],
    title => "memory pages",
    style => "lines",
    axes => "x1y2",
  ),
  Chart::Gnuplot::DataSet->new(
    xdata => \@time,
    ydata => [ map { $_ / 100 } @unes ],
    title => "routes processed ( /100 )",
    style => "lines",
    axes => "x1y2",
  ),
);
