#!/bin/bash

SRC=$(git rev-parse --show-toplevel)
PERF=$(readlink -f $(dirname $0))

testdir() {
  local WHAT=$1
  local COMMIT=$2
  if ! [ -e $PERF/test-$WHAT ]; then
    echo "Unknown test: $WHAT"
    exit 2
  fi

  if [ -z "$COMMIT" ]; then
    COMMIT="HEAD"
  fi

  local CMH=$(git rev-parse $COMMIT)

  if [ -z "$CMH" ]; then
    echo "Unknown commit: $COMMIT"
  fi

  readlink -f testdata-$WHAT-$CMH
}

