#!/bin/bash

set -e

LOC=$(dirname $0)
CONF=${1:-${LOC}/perf-test-all.conf}

./bird -lc $CONF -P perftest.pid

for p in $(./birdc -l show protocols | sed -rn 's/(\S+)\s+Perf\s+.*/\1/p'); do
  ./birdc -l enable $p
  tail -f perftest.log | while read dd; do
    echo $dd
    case $dd in
      *\ $p\ done\ with\ *) echo "protocol $p done"; break ;;
      *\<BUG\>*) echo "something nasty happened"; break ;;
    esac
  done
  ./birdc -l disable $p
done

./birdc -l down
