#!/bin/bash
REV=$1
cd $GIT_WORK_TREE

pushd /var/lib/virt/nfs
rsync -a --exclude=.git $(readlink -f $GIT_WORK_TREE) /var/lib/virt/nfs/bird-test-$REV

rm -f rc/misc-at{dL,dR,d,c,o,f,n,g}-{4,6}-conf
touch rc/misc-at{dL,dR,d,c,o,f,n,g}-{4,6}-conf

declare -a MACH=( dL dR d c o f n g )
declare -a TOK=( {dL,dR,d,c,o,f,n,g}-{4,6} )
declare -A IPA=(
  [dL-4]=10.55.254.1 \
  [dR-4]=10.55.255.1 \
  [d-4]=10.55.1.1 \
  [o-4]=10.55.2.1 \
  [f-4]=10.55.3.1 \
  [n-4]=10.55.4.1 \
  [c-4]=10.55.5.1 \
  [g-4]=10.55.6.1 \
  [dL-6]="fd01:55:fffe::1" \
  [dR-6]="fd01:55:ffff::1" \
  [d-6]="fd01:55:1::1" \
  [o-6]="fd01:55:2::1" \
  [f-6]="fd01:55:3::1" \
  [n-6]="fd01:55:4::1" \
  [c-6]="fd01:55:5::1" \
  [g-6]="fd01:55:6::1" \
)
  
declare -A SR=( \
  [dL-4]="10.56.254.0/24 via 10.55.254.55" \
  [dR-4]="10.56.255.0/24 via 10.55.255.55" \
  [d-4]="10.56.1.0/24 via 10.55.1.55" \
  [o-4]="10.56.2.0/24 via 10.55.2.55" \
  [f-4]="10.56.3.0/24 via 10.55.3.55" \
  [n-4]="10.56.4.0/24 via 10.55.4.55" \
  [c-4]="10.56.5.0/24 via 10.55.5.55" \
  [g-4]="10.56.6.0/24 via 10.55.6.55" \
  [dL-6]="fd01:56:fffe::/64 via fd01:55:fffe::55" \
  [dR-6]="fd01:56:ffff::/64 via fd01:55:ffff::55" \
  [d-6]="fd01:56:1::/64 via fd01:55:1::55" \
  [o-6]="fd01:56:2::/64 via fd01:55:2::55" \
  [f-6]="fd01:56:3::/64 via fd01:55:3::55" \
  [n-6]="fd01:56:4::/64 via fd01:55:4::55" \
  [c-6]="fd01:56:5::/64 via fd01:55:5::55" \
  [g-6]="fd01:56:6::/64 via fd01:55:6::55" \
)

function cf() {
  local -a AR
  while [ "$1" != "--" ]; do
    AR+=( $1 )
    shift
  done

  if [ -z "${AR[@]}" ]; then
    AR=( ${TOK[@]} )
  fi

  shift

  (echo "# marker $@"; "$@") | tee -a $( for F in ${AR[@]}; do echo rc/misc-at$F-conf; done ) #> /dev/null
}

function cfe() {
  cf -- echo "$@"
}

function cfc() {
  cf -- cat
}

for T in ${TOK[@]}; do
  cf $T -- echo "log \"/mnt/nfs/tmp/bird-at$T.log\" all;"
  cf $T -- echo "router id ${IPA[${T%%-*}-4]};"
done

cfe "# marker"

cfc <<EOF
#debug protocols all;

protocol device {
  scan time 10;
}

protocol kernel {
#	learn;
#	persist;
#	import all;
	export all;
	scan time 20;
}

EOF

for T in ${TOK[@]}; do
  cf $T -- cat <<EOF
table bt;

protocol static {
	import all;
	route ${SR[$T]};
}
EOF
done

cfc <<EOF
protocol bfd {
}

protocol ospf {
	import all;
	export all;
	area 0 {
		interface "INAME" { hello 5; type ptp; cost ICOST; bfd; };
	};
}
EOF

cf dL-4 -- cat <<EOF
protocol bgp {
	local 192.168.225.162 as 65123;
	neighbor 192.168.192.1 as 65534;
	import all;
	export none;
	table bt;
	igp table master;
}
EOF

cf dL-6 -- cat <<EOF
protocol bgp {
	local 2001:1488:a001::225:162 as 65123;
	neighbor 2001:1488:a001::1 as 65534;
	import all;
	export none;
	table bt;
	igp table master;
}
EOF

for T in {dL,dR}; do
  cf $T-4 -- cat <<EOF
template bgp bc {
	local ${IPA[$T-4]} as 65123;
	import all;
	export all;
	table bt;
	igp table master;
	next hop self;
}
EOF

  cf $T-6 -- cat <<EOF
template bgp bc {
	local ${IPA[$T-6]} as 65123;
	import all;
	export all;
	table bt;
	igp table master;
	next hop self;
}
EOF
done

for M in ${MACH[@]}; do
  case $M in dL|dR) continue ;; esac

  for D in dL dR; do
    cf $D-4 -- cat <<EOF
protocol bgp from bc {
	neighbor ${IPA[$M-4]} as 65123;
}
EOF

    cf $D-6 -- cat <<EOF
protocol bgp from bc {
	neighbor ${IPA[$M-6]} as 65123;
}
EOF

    cf $M-4 -- cat <<EOF
protocol bgp {
	local ${IPA[$M-4]} as 65123;
	neighbor ${IPA[$D-4]} as 65123;
	import all;
	export all;
	table bt;
	igp table master;
}
EOF

    cf $M-6 -- cat <<EOF
protocol bgp {
	local ${IPA[$M-6]} as 65123;
	neighbor ${IPA[$D-6]} as 65123;
	import all;
	export all;
	table bt;
	igp table master;
}
EOF
  done
done


for T in ${MACH[@]}; do
  cat <<'EOF' > rc/rc-loc-at$T
OSPF_INAME_SED="x;"
echo "Interface list:" ${INTERFACES[@]}

for I in ${INTERFACES[@]}; do
  case $UNAME in
    netbsd|openbsd|freebsd) COST=$((0x$(ifconfig ${I%%;*} | md5) % 75 + 150)) ;;
    linux)	  COST=$((0x$(ip addr show dev ${I%%;*} | md5) % 75 + 150)) ;;
  esac
  OSPF_INAME_SED="$OSPF_INAME_SED G; s/INAME/${I%%;*}/; s/ICOST/$COST/;"
done

OSPF_INAME_SED="$OSPF_INAME_SED x; s/.*//; x;"

SED_PATTERN="$SED_PATTERN /INAME/ { $OSPF_INAME_SED };"

echo "Sed pattern: $SED_PATTERN"
CF4="/mnt/nfs/rc/misc-$HOSTNAME-4-conf"
CF6="/mnt/nfs/rc/misc-$HOSTNAME-6-conf"

sed "$SED_PATTERN" $CF4 > /etc/bird4.conf
sed "$SED_PATTERN" $CF6 > /etc/bird6.conf
EOF
  echo "rsync --exclude=.git -a /mnt/nfs/bird-test-$REV/ /tmp/bird4" >> rc/rc-loc-at$T
  echo "rsync --exclude=.git -a /mnt/nfs/bird-test-$REV/ /tmp/bird6" >> rc/rc-loc-at$T
  cat <<'EOF' >> rc/rc-loc-at$T
cd /tmp/bird4
$AUTOCONF
./configure --sysconfdir=/etc --with-runtimedir=/run --with-suffix=4
#./configure --enable-debug
#sed -e 's/-g -O2/-g3 -O0/' -i obj/Rules
$MAKE
$MAKE install
PATH=$PATH:/usr/local/sbin
ulimit -c unlimited
bird4

cd /tmp/bird6
$AUTOCONF
./configure --sysconfdir=/etc --with-runtimedir=/run --enable-ipv6 --with-suffix=6
#./configure --enable-debug
#sed -e 's/-g -O2/-g3 -O0/' -i obj/Rules
$MAKE
$MAKE install
PATH=$PATH:/usr/local/sbin
ulimit -c unlimited
bird6

EOF
done

vctl restart -m $( for T in ${MACH[@]}; do echo at$T; done )
